export enum Department {
  ALTA_VERAPAZ = 'ALTA_VERAPAZ',
  BAJA_VERAPAZ = 'BAJA_VERAPAZ',
  CHIMALTENANGO = 'CHIMALTENANGO',
  EL_PROGRESO = 'EL_PROGRESO',
  ESCUINTLA = 'ESCUINTLA',
  GUATEMALA = 'GUATEMALA',
  HUEHUETENANGO = 'HUEHUETENANGO',
  IZABAL = 'IZABAL',
  JALAPA = 'JALAPA',
  JUTIAPA = 'JUTIAPA',
  PETEN = 'PETEN',
  QUETZALTENANGO = 'QUETZALTENANGO',
  QUICHE = 'QUICHE',
  RETALHULEU = 'RETALHULEU',
  SACATEPEQUEZ = 'SACATEPEQUEZ',
  SAN_MARCOS = 'SAN_MARCOS',
  SANTA_ROSA = 'SANTA_ROSA',
  SOLOLA = 'SOLOLA',
  SUCHITEPEQUEZ = 'SUCHITEPEQUEZ',
  TOTONICAPAN = 'TOTONICAPAN',
  ZACAPA = 'ZACAPA',
}

export enum Country {
  GUATEMALA = 'GUATEMALA',
}
